### ISSUE TITLE
Contacts Error Message Not Consistent with other error messaging

### ISSUE THREAD

**Issue by wonderchook** [Cadasta/cadasta-platform#364]
Should match other error messaging. 

![contacts-error](https://cloud.githubusercontent.com/assets/67992/16709249/d51846f2-45bf-11e6-8848-eef51a82684e.jpg)

**Comment by seav** [comment]
It seems this is already resolved on master?
![screen shot 2016-07-20 at 17 36 19](https://cloud.githubusercontent.com/assets/873653/16982101/bf0c9a36-4ea0-11e6-80bd-b7635d30d810.png)
![screen shot 2016-07-20 at 17 36 29](https://cloud.githubusercontent.com/assets/873653/16982100/bf0b450a-4ea0-11e6-9f97-10c4fad961ac.png)
![screen shot 2016-07-20 at 17 36 41](https://cloud.githubusercontent.com/assets/873653/16982102/bf11ff62-4ea0-11e6-85c0-ddcb2be4e1a1.png)

**Comment by clash99** [comment]
I was looking at this quite a bit yesterday.  The problem right now is that the error creates a separate row, so even when you remove the contact below, the error remains.  Ideally the message would be in the same row as the fields but given that it spans columns, it makes it more difficult.  And to have the delete button span rows is more difficult too.   I'll try to resolve this today.  Let me know if you have any ideas...  this contacts widget has a lot of little issues.

**Comment by seav** [comment]
@clash99, I'm trying to take a stab at this. I have a prototype UI but I haven't made the JavaScript work yet. But before I tinker with the JS, do you think the following UI for error messaging in the contacts form is OK?

![screen shot 2016-07-22 at 20 39 10](https://cloud.githubusercontent.com/assets/873653/17057482/ca184c2e-504c-11e6-8685-548421e78df4.png)

**Comment by clash99** [comment]
I think this is right on the money!

**Comment by seav** [comment]
OK, thanks! I'll continue working on this.

**Comment by seav** [comment]
Closed by #505
